[package]
name = "carose"
version = "0.1.0"
edition = "2024"
readme = "README.md"
license = "MIT"
repository = "https://github.com/RoseBlume/carose"

[dependencies]
image = "0.25.9"
minifb = "0.28.0"
rand = "0.9.2"
rodio = "0.21.1"



